import { NextRequest, NextResponse } from 'next/server';
import { sendEmail } from '@/lib/email/send';

interface AdditionalWork {
  id: string;
  date: Date;
  amount: number;
  description: string;
}

interface Payment {
  id: string;
  date: Date;
  amount: number;
  paymentMethodId: string;
}

interface ObjectExpense {
  id: string;
  amount: number;
  description?: string;
  categoryName?: string;
  paymentMethodName?: string;
  date: Date;
}

// Translations
const translations = {
  el: {
    subject: 'Αναφορά Οικονομικών Έργου',
    title: 'Αναφορά Οικονομικών Έργου',
    objectName: 'Έργο',
    contractPrice: 'Συμβατική Τιμή',
    additionalWorks: 'Πρόσθετες Εργασίες',
    actualPrice: 'Πραγματική Τιμή',
    payments: 'Πληρωμές',
    balance: 'Υπόλοιπο',
    expenses: 'Έξοδα',
    debt: 'Οφειλή',
    closed: 'Εξοφλημένο',
    overpaid: 'Υπερπληρωμή',
    footer: 'Αυτό το email δημιουργήθηκε αυτόματα από το ΑΠΑΛΛΑΚΤΗΣ',
  },
  ru: {
    subject: 'Финансовый отчёт по объекту',
    title: 'Финансовый отчёт по объекту',
    objectName: 'Объект',
    contractPrice: 'Договорная цена',
    additionalWorks: 'Дополнительные работы',
    actualPrice: 'Фактическая цена',
    payments: 'Платежи',
    balance: 'Баланс',
    expenses: 'Расходы',
    debt: 'Долг',
    closed: 'Оплачено',
    overpaid: 'Переплата',
    footer: 'Это письмо автоматически сгенерировано ΑΠΑΛΛΑΚΤΗΣ',
  },
  en: {
    subject: 'Object Finance Report',
    title: 'Object Finance Report',
    objectName: 'Object',
    contractPrice: 'Contract Price',
    additionalWorks: 'Additional Works',
    actualPrice: 'Actual Price',
    payments: 'Payments',
    balance: 'Balance',
    expenses: 'Expenses',
    debt: 'Debt',
    closed: 'Paid',
    overpaid: 'Overpaid',
    footer: 'This email was automatically generated by ΑΠΑΛΛΑΚΤΗΣ',
  },
};

function formatEuro(amount: number): string {
  return new Intl.NumberFormat('el-GR', {
    style: 'currency',
    currency: 'EUR',
  }).format(amount);
}

function generateObjectFinanceReportHTML(
  objectName: string,
  contractPrice: number,
  additionalWorks: AdditionalWork[],
  totalAdditionalWorks: number,
  actualPrice: number,
  payments: Payment[],
  totalPayments: number,
  balance: number,
  expenses: ObjectExpense[],
  totalExpenses: number,
  locale: string
): string {
  const t = translations[locale as keyof typeof translations] || translations.el;

  const balanceStatus = balance > 0.01 ? 'debt' : balance < -0.01 ? 'overpaid' : 'closed';
  const balanceColor = balanceStatus === 'debt' ? '#ff6a1a' : balanceStatus === 'overpaid' ? '#daf3f6' : '#25D366';
  const balanceTextColor = balanceStatus === 'overpaid' ? '#01312d' : 'white';
  const balanceLabel = balanceStatus === 'debt' ? t.debt : balanceStatus === 'closed' ? t.closed : t.overpaid;

  return `
<!DOCTYPE html>
<html lang="${locale}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${t.title}</title>
</head>
<body style="font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px;">
  <table width="100%" cellpadding="0" cellspacing="0" style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden;">
    <!-- Header -->
    <tr>
      <td style="background: linear-gradient(135deg, #01312d 0%, #025951 100%); padding: 40px 20px; text-align: center;">
        <img src="https://apallaktis.com/Apallaktis.photos/apallaktis-logo-orange@2x.png" alt="ΑΠΑΛΛΑΚΤΗΣ" style="width: 180px; height: auto; margin-bottom: 20px;" />
        <h1 style="color: #ff8f0a; margin: 0; font-size: 28px;">${t.title}</h1>
        <p style="color: #daf3f6; margin: 10px 0 0 0; font-size: 18px;">${t.objectName}: ${objectName}</p>
      </td>
    </tr>

    <!-- Content -->
    <tr>
      <td style="padding: 30px;">
        <!-- Contract Price -->
        <div style="background-color: #daf3f6; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
          <h2 style="color: #01312d; margin: 0 0 10px 0; font-size: 18px;">${t.contractPrice}</h2>
          <p style="color: #ff6a1a; margin: 0; font-size: 24px; font-weight: bold;">${formatEuro(contractPrice)}</p>
        </div>

        <!-- Additional Works -->
        <div style="background-color: #daf3f6; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
          <h2 style="color: #01312d; margin: 0 0 10px 0; font-size: 18px;">${t.additionalWorks}</h2>
          <p style="color: #01312d; margin: 0; font-size: 24px; font-weight: bold;">+${formatEuro(totalAdditionalWorks)}</p>
        </div>

        <!-- Actual Price -->
        <div style="background-color: #daf3f6; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
          <h2 style="color: #01312d; margin: 0 0 10px 0; font-size: 18px;">${t.actualPrice}</h2>
          <p style="color: #ff6a1a; margin: 0; font-size: 24px; font-weight: bold;">${formatEuro(actualPrice)}</p>
        </div>

        <!-- Payments -->
        <div style="background-color: #daf3f6; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
          <h2 style="color: #01312d; margin: 0 0 10px 0; font-size: 18px;">${t.payments}</h2>
          <p style="color: #01312d; margin: 0; font-size: 24px; font-weight: bold;">-${formatEuro(totalPayments)}</p>
        </div>

        <!-- Balance -->
        <div style="background-color: ${balanceColor}; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
          <h2 style="color: ${balanceTextColor}; margin: 0 0 10px 0; font-size: 18px;">${t.balance}</h2>
          <p style="color: ${balanceTextColor}; margin: 0; font-size: 32px; font-weight: bold;">${formatEuro(Math.abs(balance))}</p>
          <p style="color: ${balanceTextColor}; margin: 10px 0 0 0; font-size: 18px; font-weight: bold;">${balanceLabel}</p>
        </div>

        <!-- Expenses -->
        <div style="background-color: #e2f1dd; border-radius: 8px; padding: 20px;">
          <h2 style="color: #01312d; margin: 0 0 10px 0; font-size: 18px;">${t.expenses}</h2>
          <p style="color: #ff6a1a; margin: 0; font-size: 24px; font-weight: bold;">${formatEuro(totalExpenses)}</p>
        </div>
      </td>
    </tr>

    <!-- Footer -->
    <tr>
      <td style="background-color: #f9f9f9; padding: 20px; text-align: center; border-top: 1px solid #e0e0e0;">
        <p style="font-size: 12px; color: #999; margin: 0;">${t.footer}</p>
        <p style="font-size: 12px; color: #999; margin: 10px 0 0 0;">
          © 2026 ΑΠΑΛΛΑΚΤΗΣ. All rights reserved.
        </p>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      email,
      objectName,
      contractPrice,
      additionalWorks,
      totalAdditionalWorks,
      actualPrice,
      payments,
      totalPayments,
      balance,
      expenses,
      totalExpenses,
      locale,
    } = body;

    if (!email || !objectName) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const t = translations[locale as keyof typeof translations] || translations.el;
    const html = generateObjectFinanceReportHTML(
      objectName,
      contractPrice || 0,
      additionalWorks || [],
      totalAdditionalWorks || 0,
      actualPrice || 0,
      payments || [],
      totalPayments || 0,
      balance || 0,
      expenses || [],
      totalExpenses || 0,
      locale || 'el'
    );

    const success = await sendEmail({
      to: email,
      subject: `${t.subject}: ${objectName}`,
      html,
    });

    if (success) {
      return NextResponse.json({ success: true });
    } else {
      return NextResponse.json(
        { error: 'Failed to send email' },
        { status: 500 }
      );
    }
  } catch (error) {
    console.error('Error sending object finance report email:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
