import { NextRequest, NextResponse } from 'next/server';
import { sendEmail } from '@/lib/email/send';

interface AnalysisData {
  totalIncome: number;
  incomeByPaymentMethod: { [key: string]: number };
  totalObjectExpenses: number;
  objectExpensesByCategory: { [key: string]: number };
  totalGlobalExpenses: number;
  globalExpensesByCategory: { [key: string]: number };
  totalExpenses: number;
  expensesByPaymentMethod: { [key: string]: number };
  netProfit: number;
  totalDebts: number;
  debtsByObject: { objectName: string; debt: number }[];
  totalObjects: number;
  openObjects: number;
  closedInPeriod: number;
}

// Translations
const translations = {
  el: {
    subject: 'Αναφορά Ανάλυσης',
    title: 'Αναφορά Ανάλυσης',
    period: 'Περίοδος',
    income: 'ΕΣΟΔΑ',
    objectExpenses: 'ΕΞΟΔΑ ΕΡΓΩΝ',
    globalExpenses: 'ΓΕΝΙΚΑ ΕΞΟΔΑ',
    totalExpenses: 'ΣΥΝΟΛΟ ΕΞΟΔΩΝ',
    netProfit: 'Καθαρό κέρδος',
    clientDebts: 'ΟΦΕΙΛΕΣ ΠΕΛΑΤΩΝ',
    objects: 'ΕΡΓΑ',
    totalObjects: 'Σύνολο',
    openObjects: 'Ανοιχτά',
    closedInPeriod: 'Κλεισμένα',
    footer: 'Αυτό το email δημιουργήθηκε αυτόματα από το ΑΠΑΛΛΑΚΤΗΣ',
  },
  ru: {
    subject: 'Отчёт Анализа',
    title: 'Отчёт Анализа',
    period: 'Период',
    income: 'ДОХОДЫ',
    objectExpenses: 'РАСХОДЫ ПО ОБЪЕКТАМ',
    globalExpenses: 'ГЛОБАЛЬНЫЕ РАСХОДЫ',
    totalExpenses: 'ВСЕГО РАСХОДОВ',
    netProfit: 'Чистая прибыль',
    clientDebts: 'ДОЛГИ КЛИЕНТОВ',
    objects: 'ОБЪЕКТЫ',
    totalObjects: 'Всего',
    openObjects: 'Открытых',
    closedInPeriod: 'Закрыто',
    footer: 'Это письмо автоматически сгенерировано ΑΠΑΛΛΑΚΤΗΣ',
  },
  en: {
    subject: 'Analysis Report',
    title: 'Analysis Report',
    period: 'Period',
    income: 'INCOME',
    objectExpenses: 'PROJECT EXPENSES',
    globalExpenses: 'GLOBAL EXPENSES',
    totalExpenses: 'TOTAL EXPENSES',
    netProfit: 'Net profit',
    clientDebts: 'CLIENT DEBTS',
    objects: 'PROJECTS',
    totalObjects: 'Total',
    openObjects: 'Open',
    closedInPeriod: 'Closed',
    footer: 'This email was automatically generated by ΑΠΑΛΛΑΚΤΗΣ',
  },
};

function formatEuro(amount: number): string {
  return new Intl.NumberFormat('el-GR', {
    style: 'currency',
    currency: 'EUR',
  }).format(amount);
}

function generateAnalysisReportHTML(
  data: AnalysisData,
  dateFrom: string,
  dateTo: string,
  locale: string
): string {
  const t = translations[locale as keyof typeof translations] || translations.el;
  const profitColor = data.netProfit >= 0 ? '#25D366' : '#ff6a1a';

  return `
<!DOCTYPE html>
<html lang="${locale}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${t.title}</title>
</head>
<body style="font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px;">
  <table width="100%" cellpadding="0" cellspacing="0" style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden;">
    <!-- Header -->
    <tr>
      <td style="background: linear-gradient(135deg, #01312d 0%, #025951 100%); padding: 40px 20px; text-align: center;">
        <img src="https://apallaktis.com/Apallaktis.photos/apallaktis-logo-orange@2x.png" alt="ΑΠΑΛΛΑΚΤΗΣ" style="width: 180px; height: auto; margin-bottom: 20px;" />
        <h1 style="color: #ff8f0a; margin: 0; font-size: 28px;">${t.title}</h1>
        <p style="color: #daf3f6; margin: 10px 0 0 0; font-size: 14px;">${t.period}: ${dateFrom} - ${dateTo}</p>
      </td>
    </tr>

    <!-- Content -->
    <tr>
      <td style="padding: 30px;">
        <!-- Income -->
        <div style="background-color: #b0ffd1; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
          <h2 style="color: #01312d; margin: 0 0 10px 0; font-size: 18px;">${t.income}</h2>
          <p style="color: #01312d; margin: 0; font-size: 24px; font-weight: bold;">${formatEuro(data.totalIncome)}</p>
        </div>

        <!-- Object Expenses -->
        <div style="background-color: #daf3f6; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
          <h2 style="color: #01312d; margin: 0 0 10px 0; font-size: 18px;">${t.objectExpenses}</h2>
          <p style="color: #01312d; margin: 0; font-size: 24px; font-weight: bold;">${formatEuro(data.totalObjectExpenses)}</p>
        </div>

        <!-- Global Expenses -->
        <div style="background-color: #daf3f6; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
          <h2 style="color: #01312d; margin: 0 0 10px 0; font-size: 18px;">${t.globalExpenses}</h2>
          <p style="color: #01312d; margin: 0; font-size: 24px; font-weight: bold;">${formatEuro(data.totalGlobalExpenses)}</p>
        </div>

        <!-- Total Expenses -->
        <div style="background-color: #daf3f6; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
          <h2 style="color: #01312d; margin: 0 0 10px 0; font-size: 18px;">${t.totalExpenses}</h2>
          <p style="color: #01312d; margin: 0; font-size: 24px; font-weight: bold;">${formatEuro(data.totalExpenses)}</p>
        </div>

        <!-- Net Profit -->
        <div style="background-color: ${data.netProfit >= 0 ? '#b0ffd1' : '#ffcdd2'}; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
          <h2 style="color: #01312d; margin: 0 0 10px 0; font-size: 18px;">${t.netProfit}</h2>
          <p style="color: ${profitColor}; margin: 0; font-size: 32px; font-weight: bold;">${formatEuro(data.netProfit)}</p>
        </div>

        <!-- Client Debts -->
        <div style="background-color: #fff3e0; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
          <h2 style="color: #01312d; margin: 0 0 10px 0; font-size: 18px;">${t.clientDebts}</h2>
          <p style="color: #ff6a1a; margin: 0; font-size: 24px; font-weight: bold;">${formatEuro(data.totalDebts)}</p>
        </div>

        <!-- Objects Stats -->
        <div style="background-color: #f5f5f5; border-radius: 8px; padding: 20px;">
          <h2 style="color: #01312d; margin: 0 0 15px 0; font-size: 18px;">${t.objects}</h2>
          <table width="100%" style="border-collapse: collapse;">
            <tr>
              <td style="text-align: center; padding: 10px;">
                <p style="margin: 0; font-size: 28px; font-weight: bold; color: #01312d;">${data.totalObjects}</p>
                <p style="margin: 5px 0 0 0; font-size: 12px; color: #666;">${t.totalObjects}</p>
              </td>
              <td style="text-align: center; padding: 10px;">
                <p style="margin: 0; font-size: 28px; font-weight: bold; color: #25D366;">${data.openObjects}</p>
                <p style="margin: 5px 0 0 0; font-size: 12px; color: #666;">${t.openObjects}</p>
              </td>
              <td style="text-align: center; padding: 10px;">
                <p style="margin: 0; font-size: 28px; font-weight: bold; color: #ff6a1a;">${data.closedInPeriod}</p>
                <p style="margin: 5px 0 0 0; font-size: 12px; color: #666;">${t.closedInPeriod}</p>
              </td>
            </tr>
          </table>
        </div>
      </td>
    </tr>

    <!-- Footer -->
    <tr>
      <td style="background-color: #f9f9f9; padding: 20px; text-align: center; border-top: 1px solid #e0e0e0;">
        <p style="font-size: 12px; color: #999; margin: 0;">${t.footer}</p>
        <p style="font-size: 12px; color: #999; margin: 10px 0 0 0;">
          © 2026 ΑΠΑΛΛΑΚΤΗΣ. All rights reserved.
        </p>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { email, dateFrom, dateTo, data, locale } = body;

    if (!email || !dateFrom || !dateTo || !data) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const t = translations[locale as keyof typeof translations] || translations.el;
    const html = generateAnalysisReportHTML(data, dateFrom, dateTo, locale || 'el');

    const success = await sendEmail({
      to: email,
      subject: `${t.subject} (${dateFrom} - ${dateTo})`,
      html,
    });

    if (success) {
      return NextResponse.json({ success: true });
    } else {
      return NextResponse.json(
        { error: 'Failed to send email' },
        { status: 500 }
      );
    }
  } catch (error) {
    console.error('Error sending analysis report email:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
